### ISSUE TITLE
Add logging specific elasticsearch backend

### ISSUE THREAD

**Issue by godber** [terascope/terafoundation#115]
The operator should be able to specify an alternative backend ES to write logs to.  If the `logging_server` is set, then the logs should go there.  If it is `null` and `logging` = `elasticsearch` then the logs should just go to the state backend like it does now.

**Comment by godber** [comment]
There is already `logging_connection` which claims:

> If storing logs to elasticsearch, use this parameter to specify which endpoint it will use in the connectors configuration

**Comment by jsnoble** [comment]
as stated this is possible through the logging_connection parameter
