### ISSUE TITLE
workers are executing bootstrap script

### ISSUE THREAD

**Issue by jsnoble** [terascope/terafoundation#3]
after account creation on set up -b. The account is made, however later on the workers try to create the same user as well leading to errors.

 Bootstrap: creating a default admin account with password 'admin'
 Bootstrap: creating a default admin account with password 'admin'
 Bootstrap: creating a default admin account with password 'admin'
 Bootstrap: creating a default admin account with password 'admin'

Failure creating account MongoError: E11000 duplicate key error index: m2m.accounts.$email_1 dup key: { : "admin@example.com" }
Failure creating account MongoError: E11000 duplicate key error index: m2m.accounts.$email_1 dup key: { : "admin@example.com" }
Failure creating account MongoError: E11000 duplicate key error index: m2m.accounts.$email_1 dup key: { : "admin@example.com" }
Failure creating account MongoError: E11000 duplicate key error index: m2m.accounts.$email_1 dup key: { : "admin@example.com" }

**Comment by kstaken** [comment]
fixed in da52c37
