### ISSUE TITLE
Upgrade elasticsearch client for ES5 compatibility

### ISSUE THREAD

**Issue by godber** [terascope/terafoundation#68]
The elasticsearch client should be upgraded to version `^12.0.0` and verified to remain compatible with the following versions of elasticsearch:

* Elasticsearch 1.7
* Elasticsearch 2.3
* Elasticsearch 2.4
* Elasticsearch 5.0

**Comment by kstaken** [comment]
Would be nice to support something from 1.x for some period of time. The first jobs we ran were on 1.7.x so maybe from there would be good.

**Comment by kstaken** [comment]
Think we can close this now.
