### ISSUE TITLE
Remove express from package.json

### ISSUE THREAD

**Issue by godber** [terascope/terafoundation#88]
Express appears to be present in the `package.json` file needlessly.  From git blame it looks like it came from an old refactor commit:

https://github.com/terascope/terafoundation/commit/9a10004e95e4810dc2ec6a3c26db6aa668d87aaf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R13

It could be required for teraserver's needs or something.

Grepping the terafoundation source for `express` show's it's not in use in this package.

**Comment by jsnoble** [comment]
this was completed in https://github.com/terascope/terafoundation/commit/7d13acbdc40b95cb9d04ec889d14d3764c20e26c
