### ISSUE TITLE
Config file applicability

### ISSUE THREAD

**Issue by erik-stephens** [terascope/terafoundation#90]
While trying to figure out why certain code paths weren't firing, I discovered that [the config file settings](https://github.com/terascope/terafoundation/blob/6606ec336cc05714fa5ddb710c5b607f91626ebe/index.js#L18) do not get [passed to the master](https://github.com/terascope/terafoundation/blob/6606ec336cc05714fa5ddb710c5b607f91626ebe/index.js#L156).  Is this by design?

**Comment by jsnoble** [comment]
By the time master is called there, the validated config file is already attached to the context which is passed master. There was not a good enough reason to have to pass them in twice. (configFile changes to sysconfig on line 30 in index.js of terafoundation)

**Comment by kstaken** [comment]
Nothing actionable
